name: OpenSilver Showcase Build

env:
  virtual-directory: '/opensilvershowcase/develop/'
  app-path: 'opensilverdemos/opensilvershowcase/develop/'
  virtual-directory-release: '/opensilvershowcase/release/'
  app-path-release: 'opensilverdemos/opensilvershowcase/release/'
  deploy-service-url: 'opensilverdemos.scm.azurewebsites.net:443'
  next-release-version: '1.1.0'

on:
  workflow_dispatch:
    inputs:
      opensilver-branch:
        description: 'OpenSilver branch to use'
        default: 'develop'
        required: true

jobs:
  OpenSilverShowcaseBuild:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.1
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.202'
      - name: Clone OpenSilver repo
        uses: actions/checkout@v2
        with:
          repository: ashotkhachatryan/OpenSilver
          ref: develop
      - name: Clone OpenSilver Showcase
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run ls
        run: |
          ls -l
      - name: Restore Packages
        run: |
          ./restore-packages-opensilver.bat
          nuget restore src/OpenSilver.sln -v quiet
      - name: Build Compiler
        run: msbuild src/Compiler/Compiler/Compiler.OpenSilver.csproj -p:Configuration=SL -clp:ErrorsOnly -restore
      - name: Copy Compiler Assemblies
        run: cp src/Compiler/Compiler/bin/OpenSilver/SL/net461/OpenSilver.Compiler*dll src/packages/OpenSilver.1.0.0/tools/;
      - name: Build OpenSilver
        working-directory: build
        run: msbuild slnf/OpenSilver.slnf -p:Configuration=SL -clp:ErrorsOnly -restore
      - name: Format Version Suffix
        id: format-suffix
        run: echo "::set-output name=suffix::$(date +'%Y-%m-%d-%H%M%S')-${{ env.GITHUB_SHA_SHORT }}"
      - name: Format Package Version
        id: format-version
        run: echo "::set-output name=version::${{ env.next-release-version }}-preview-${{ steps.format-suffix.outputs.suffix }}"
      - name: Pack OpenSilver
        working-directory: build
        run: |
          mkdir temp; echo "OpenSilver ${{ steps.format-version.outputs.version }}" > temp/Version.txt
          nuget.exe pack nuspec\OpenSilver.nuspec -OutputDirectory "output/OpenSilver" -Properties "PackageId=OpenSilver;PackageVersion=${{ steps.format-version.outputs.version }};Configuration=SL;Target=OpenSilver;RepositoryUrl=https://github.com/${{ env.GITHUB_REPOSITORY_OWNER_PART }}/${{ env.GITHUB_REPOSITORY_NAME_PART }}"
      - name: Replace text develop
        if: github.ref == 'refs/heads/develop'
        run: |
          sed -i 's\<base href=\"/\" />\<base href=\"${{ env.virtual-directory }}\" />\g' OpenSilver.Samples.Showcase.Browser/wwwroot/index.html
          tail -500 OpenSilver.Samples.Showcase.Browser/wwwroot/index.html
      - name: Replace text release
        if: github.ref == 'refs/heads/throw_fix'
        run: |
          sed -i 's\<base href=\"/\" />\<base href=\"${{ env.virtual-directory-release }}\" />\g' OpenSilver.Samples.Showcase.Browser/wwwroot/index.html
          tail -500 OpenSilver.Samples.Showcase.Browser/wwwroot/index.html
      - name: Replace UserName
        run: |
          sed -i 's\USERNAME\${{ secrets.OPENSILVERDEMOSUSERNAME }}\g' OpenSilver.Samples.Showcase.Browser\Properties\PublishProfiles\publish.pubxml
      - name: Use OpenSilver version
        run: |
          dotnet add OpenSilver.Samples.Showcase.Browser\OpenSilver.Samples.Showcase.Browser.csproj package OpenSilver --version ${{ steps.format-version.outputs.version }} -s ../../../build/output/OpenSilver/
          dotnet add src\OpenSilver.Samples.Showcase.csproj package OpenSilver --version ${{ steps.format-version.outputs.version }} -s ../../../build/output/OpenSilver/
      - name: Build and Deploy develop
        if: github.ref == 'refs/heads/develop'
        run: |
          msbuild OpenSilver.Samples.Showcase.Browser\OpenSilver.Samples.Showcase.Browser.csproj /p:DeployOnBuild=true /p:PublishProfile="OpenSilver.Samples.Showcase.Browser\Properties\PublishProfiles\publish.pubxml" /p:Password=${{ secrets.OPENSILVERDEMOSUSERPWD }} /p:DeployIisAppPath=${{ env.app-path }} /p:MSDeployServiceURL=${{ env.deploy-service-url }}
      - name: Build and Deploy release
        if: github.ref == 'refs/heads/throw_fix'
        run: |
          msbuild OpenSilver.Samples.Showcase.Browser\OpenSilver.Samples.Showcase.Browser.csproj /p:DeployOnBuild=true /p:PublishProfile="OpenSilver.Samples.Showcase.Browser\Properties\PublishProfiles\publish.pubxml" /p:Password=${{ secrets.OPENSILVERDEMOSUSERPWD }} /p:DeployIisAppPath=${{ env.app-path }} /p:MSDeployServiceURL=${{ env.deploy-service-url }}